### ISSUE TITLE
Detection of jigsaw piece 

### ISSUE THREAD

**Issue by AlexanderNorup** [AlexanderNorup/Croc1-AutoSplitter#1]
In 100% you usually skip the "Level completed" screen for secret levels. The autosplitter should spilt on collection of the jigsaw and then ignore any level completed splits for 10 seconds to ensure we don't double split if the runner misses the skip.

**Comment by IsabellaNorup** [comment]
Solved in https://github.com/AlexanderNorup/Croc1-AutoSplitter/commit/6a2716814d97d762956f74bf45ee4e4dc1ecfda4
